- src/app/login/page.tsx
fix: update welcome message on login page
> fix: update welcome message on login page

- src/components/auth/authform.tsx
- src/components/navbar.tsx
> fix: sign In button

- src/app/(protected)/data-management/tarrif/page.tsx
- src/app/(protected)/layout.tsx
- src/components/auth/authform.tsx
- src/components/dashboard/MetersInstalledChart.tsx
- src/components/dashboard/SearchAndFilters.tsx
- src/components/navbar.tsx
- src/components/sidebar-nav.tsx
- src/lib/dashboardData.ts
Adding Cursor pointer to the Login.
Cursor pointer to the Dropdown menu item.
Fixing the side bar Sub menu Item.
Changing the search icon size.
Changing Card text from Allocation to Assigned.
Changes on the Meter Distribution Title to Meters "Assigned" over time and styling the Meters duration button Month, Quarter and Yearly.
Changes on Bulk Approve & Export button color in Tariff Module.
> fix: code clean up

- src/app/(protected)/data-management/meter-management/page.tsx
- src/components/auth/authform.tsx
- src/components/customermanagement/customerform.tsx
- src/components/customermanagement/customermanagement.tsx
Adding spinner on the Login button.
Re-arranging and adding customer Id on the Customer Management Table.
Making changes on the Edit Customer form in Customer Management Module.
Making changes on the Add Customer form in Customer Management Module.
Making changes on the Edit Customer form for Assigned Meter in Customer Management Module.
> fix: Updated modification by <Musa>

- src/app/(protected)/data-management/debt-management/debt-settings/page.tsx
- src/components/customermanagement/customerform.tsx
- src/components/customermanagement/customermanagement.tsx
- src/components/debt-setting/liability-table.tsx
- src/components/debt-setting/percentage-range-dialog.tsx
- src/components/mode-of-payment/mode-of-payment-table.tsx
- src/components/mode-of-payment/set-payment-dailog.tsx
fist customer clean up and debtsetting plus mode of payment clean up
> Ft/as customer&meter cleanup

- src/components/auth/authform.tsx
- made the eye login icon to sync with screen change
> fixed the issue of icon being too big on login page

- src/components/customermanagement/customermanagement.tsx
- src/components/meter-management/bulk-upload.tsx
bulkupload on customer,and edited bulk upload border to blue from gray
> feat: add bulk upload functionality to customer management

- src/components/meter-management/bulk-upload.tsx
- src/components/vending-dashboard/token-transaction-charts.tsx
- src/components/vending/token-form-dialog.tsx
fix: Fix overlapping dialog on Vending process
> feat: Enhance Pie Charts with Dynamic Tooltips & Layout Improvements

- src/app/(protected)/billing/md-prebilling/reading-sheet/page.tsx
- src/components/billing/generate-reading.tsx
- src/components/billing/meter-reading.tsx
- src/components/billing/view-meter-reading-details.tsx
- src/styles/globals.css
Adds dialog for meter reading details and new monthly/yearly filters for the table.
> feat: Implement meter reading view details and table filters

- src/app/(protected)/billing/dashboard/page.tsx
- src/components/billing/dashboard/EnergyConsumedChart.tsx
- src/components/billing/dashboard/OutstandingChart.tsx
- src/components/billing/dashboard/SearchAndFilters.tsx
- src/components/billing/dashboard/summary-cards.tsx
- src/components/sidebar-nav.tsx
added the component for the billing dashboard
> setup of the billing dashboard

- src/components/sidebar-nav.tsx
- src/components/usermanagement/adduserform.tsx
- src/components/usermanagement/edituserdialog.tsx
- updated the add user and edit user to match the design
- increased the padding of the collapsible sub menu a bit
> made update to the sidebar collapsible menu and the user management page

- src/app/(protected)/billing/billing/page.tsx
- src/components/billing/billing-table.tsx
feat: Enhance Billing Page with Dynamic Multi-Select and Reverse Bill Flow
This commit introduces significant improvements to the Billing Page, focusing on enhanced user experience for both "Generate Bill" and "Reverse Bill" functionalities.
Key changes include:
* **Refactored Multi-Select Dropdowns:** Replaced the problematic `Select` component with a custom `DropdownMenu` implementation for multi-selection within the "Generate Bill" and "Reverse Bill" dialogs. This resolves previous issues with checkbox selection and alignment, providing a robust and intuitive user experience.
* **Dynamic Dialog Elements:**
* The label and placeholder text for the multi-select dropdowns now dynamically update based on the selected filter (e.g., "Feeder," "MD," "Account No.").
* The "Proceed" button text …
> feat: Billing page

- src/app/(protected)/billing/billing/page.tsx
- src/components/billing/billing-table.tsx
- Fixed size consistency for all components (buttons, loaders, etc.)
- Ensured uniform dimensions using Tailwind CSS classes
- Adjusted responsive behavior where needed
> style: standardize component sizing across the page

- src/components/reviewandapproval/metertable.tsx
- src/components/reviewandapproval/viewmetersdetailsdialog.tsx
meters tab modified in review and approval module
> meters tab modified in review and approval module

- src/components/reviewandapproval/tarifftable.tsx
- src/components/reviewandapproval/viewtariffdetailsdialog.tsx
modified tariff tab on review and approval page
> modified tariff tab on review and approval page

- src/components/reviewandapproval/viewbanddetailsdialog.tsx
modified band tab on review and approval page
> modified band tab on review and approval page

- src/components/reviewandapproval/liabilitycausetable.tsx
- src/components/reviewandapproval/viewliabitydetailsdialog.tsx
> modified liability tab

- src/app/(protected)/hes/controlsandconfigs/meter-remote-config/page.tsx
- src/components/hes/controlsconfigs/data-collection-schedule/set-sync-schedule-dialog.tsx
- src/components/hes/controlsconfigs/meter-remote-config/change-relay-mode-dialog.tsx
- src/components/hes/controlsconfigs/meter-remote-config/configure-apn-dialog.tsx
- src/components/hes/controlsconfigs/meter-remote-config/configure-ctv-ratio-dialog.tsx
- src/components/hes/controlsconfigs/meter-remote-config/configure-ip-dialog.tsx
- src/components/hes/controlsconfigs/meter-remote-config/offline-meter-dialog.tsx
- src/components/hes/controlsconfigs/meter-remote-config/set-date-time-dialog.tsx
- src/components/hes/controlsconfigs/meter-remote-config/view-details-dialog.tsx
- src/types/meter.ts
created the table and several dialogs for the meter configuratin module
> created the table and several dialogs for the meter configuratin module

- src/components/navbar.tsx
changed the navbar background to white
> changed the navbar background to white

- src/hooks/use-meter.ts
- src/service/meter-service.ts
- src/types/meter-inventory.ts
Setup of the hooks, service and types files the route calling implemented.
> added the types, service and hooks file for the meter inventory page

- src/app/(protected)/data-management/meter-management/assign-meter/page.tsx
- src/app/(protected)/data-management/meter-management/meter-inventory/page.tsx
- src/app/(protected)/data-management/meter-management/meter-manufacturer/page.tsx
- src/app/(protected)/data-management/meter-management/meters/page.tsx
- src/components/audit-log/audit-log-details.tsx
- src/components/meter-management/add-edit-meter-dialog.tsx
- src/components/meter-management/migrate-meter-dialog.tsx
- src/components/meter-management/view-meter-info-dialog.tsx
- src/components/meter-management/view-meters-details-dialog.tsx
- src/components/ui/sonner.tsx
- src/hooks/use-ReviewApproval.ts
- src/hooks/use-meter.ts
- src/lib/dashboardData.ts
- src/service/meter-service.ts
- src/types/meter-inventory.ts
- src/types/meter.ts
meter inventory module fetching records from backend
> Ft gr meter inventory
